### PR TITLE
my_printf

### PR DESCRIPTION
**Pull request by asr0r0**

### CODE REVIEW

**Review by simple-lemon — CHANGES_REQUESTED** [review]
Printf implementatsiyasida printf() funksiyasini ishlatish mumkin emas 
printf oilasiga mansub funksiyalarni ham
Makefile yoq!

**Comment by asr0r0** [comment]
Xo'p chunarli . To'g'irladim Makefile ham qo'shdim

Sesh, 20-fev, 2024, 10:42 Alimov Otabek ***@***.***>:

**Comment by simple-lemon** [comment]
boshqattan yuklang bu pull request yopilgan

**Comment by asr0r0** [comment]
Xakimbayev asror
#43 opened 2 hours ago by asr0r0 yuklaganman

Sesh, 20-fev, 2024, 16:31 Alimov Otabek ***@***.***>:

**Comment by simple-lemon** [comment]
ok

**Pull request closed without merging**
